# Generated by Django 4.1.3 on 2024-05-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document_id',
            field=models.CharField(default=1111, max_length=255),
            preserve_default=False,
        ),
    ]
