# Generated by Django 4.1.3 on 2023-02-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_useractivities'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
