# Generated by Django 4.1.3 on 2024-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_customuser_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_goal',
            field=models.FloatField(default=0.0),
        ),
    ]
