# Generated by Django 4.1.3 on 2024-05-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_customuser_daily_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CC'), ('PA', 'PA'), ('NIT', 'NIT'), ('CE', 'CC'), ('TI', 'TI')], default='CC', max_length=3),
        ),
    ]
