# Generated by Django 4.1.3 on 2024-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_alter_customuser_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('posAdmin', 'posAdmin'), ('shopAdmin', 'shopAdmin'), ('sales', 'sales'), ('supportSales', 'supportSales'), ('storageAdmin', 'storageAdmin')], max_length=12),
        ),
    ]
