# Generated by Django 4.1.3 on 2023-03-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
