# Generated by Django 4.1.3 on 2024-06-13 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_alter_company_dian_token_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivities',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='user_control.company'),
            preserve_default=False,
        ),
    ]
