# Generated by Django 4.1.3 on 2024-07-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_company_customuser_company_useractivities_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
