# Generated by Django 4.1.3 on 2024-06-13 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0008_useractivities_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_company', to='user_control.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivities',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities_company', to='user_control.company'),
        ),
    ]
