# Generated by Django 4.1.3 on 2024-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0008_company_logo_company_phone_company_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dian_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'nit'), name='unique_name_nit'),
        ),
    ]
