# Generated by Django 4.1.3 on 2024-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0009_alter_company_dian_token_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
