# Generated by Django 4.1.3 on 2024-10-31 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.PositiveIntegerField()),
                ('name_api', models.CharField(max_length=100)),
                ('type_api', models.CharField(max_length=100)),
                ('name_kiospot', models.CharField(max_length=100, null=True)),
                ('default', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
