# Generated by Django 4.1.3 on 2024-05-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dianresolution',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
