# Generated by Django 4.1.3 on 2024-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_dianresolution_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianresolution',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
