# Generated by Django 4.1.3 on 2023-03-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
    ]
