# Generated by Django 4.1.3 on 2023-03-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_remove_invoice_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='Invoice',
            new_name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='created_at',
        ),
    ]
