# Generated by Django 4.1.3 on 2023-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0005_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='customerId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='customerName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
