# Generated by Django 4.1.3 on 2024-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_provider_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterminal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
