# Generated by Django 4.1.3 on 2023-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_invoiceitem_customerid_invoiceitem_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='customerName',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customerId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customerName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
