# Generated by Django 4.1.3 on 2024-05-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_paymentterminal_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dian_document_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='dian_resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dian_resolution', to='app_control.dianresolution'),
        ),
    ]
