# Generated by Django 4.1.3 on 2024-05-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0008_remove_invoice_dian_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='cost_center',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
