# Generated by Django 4.1.3 on 2023-04-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0010_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
