# Generated by Django 4.1.3 on 2024-05-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0010_inventorygroup_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterminal',
            name='account_code',
            field=models.CharField(max_length=200),
        ),
    ]
