# Generated by Django 4.1.3 on 2023-04-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0012_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('cash', 'cash'), ('creditCard', 'creditCard'), ('debitCard', 'debitCard'), ('nequi', 'nequi'), ('bankTransfer', 'bankTransfer')], max_length=255),
        ),
    ]
