# Generated by Django 4.1.3 on 2024-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0012_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='goal_type',
            field=models.CharField(choices=[('diary', 'Diary'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20, unique=True),
        ),
    ]
