# Generated by Django 4.1.3 on 2024-05-30 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0013_alter_goals_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CC'), ('PA', 'PA'), ('NIT', 'NIT'), ('CE', 'CC'), ('TI', 'TI')], default='CC', max_length=3),
        ),
    ]
