# Generated by Django 4.1.3 on 2023-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0013_alter_paymentmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='transaction_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
