# Generated by Django 4.1.3 on 2023-04-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0014_alter_paymentmethod_transaction_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='amount',
            field=models.FloatField(),
        ),
    ]
