# Generated by Django 4.1.3 on 2024-06-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0007_company_customuser_company_useractivities_company'),
        ('app_control', '0015_customer_city_alter_customer_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='dianresolution',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolution_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='goals',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goals_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='inventorygroup',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_group_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_item_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_method_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='paymentterminal',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_terminal_company', to='user_control.company'),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_company', to='user_control.company'),
        ),
    ]
