# Generated by Django 4.1.3 on 2023-04-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0015_alter_paymentmethod_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='isDollar',
            field=models.BooleanField(default=False),
        ),
    ]
