# Generated by Django 4.1.3 on 2024-07-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0016_customer_company_dianresolution_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dianresolution',
            name='document_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_type',
            field=models.CharField(choices=[('diary', 'Diary'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventorygroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentterminal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('document_id', 'company'), name='unique_customer_document_id'),
        ),
        migrations.AddConstraint(
            model_name='dianresolution',
            constraint=models.UniqueConstraint(fields=('document_number', 'company'), name='unique_dian_document_number'),
        ),
        migrations.AddConstraint(
            model_name='goals',
            constraint=models.UniqueConstraint(fields=('goal_type', 'company'), name='unique_goal_type'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_code'),
        ),
        migrations.AddConstraint(
            model_name='inventorygroup',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_group_name'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'company'), name='unique_invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentterminal',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_name+'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='unique_provider_name'),
        ),
    ]
