# Generated by Django 4.1.3 on 2023-04-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0016_invoice_isdollar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='isDollar',
            new_name='is_dollar',
        ),
    ]
