# Generated by Django 4.1.3 on 2023-04-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0018_invoiceitem_amount_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='amount_usd',
            new_name='usd_amount',
        ),
    ]
