# Generated by Django 5.0.6 on 2024-09-14 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0018_inventorymovement'),
        ('user_control', '0009_alter_company_dian_token_alter_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='delivery_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('overrided', 'overrided')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='InventoryMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('overrided', 'overrided')], default='pending', max_length=255)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('delivery_notes', models.TextField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_movement_item_company', to='user_control.company')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_item', to='app_control.inventory')),
                ('inventory_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movement_items', to='app_control.inventorymovement')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
