# Generated by Django 4.1.3 on 2023-04-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0020_alter_paymentmethod_options_paymentmethod_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='amount',
            new_name='back_amount',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='paid_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='received_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
