# Generated by Django 4.1.3 on 2023-04-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0022_rename_back_amount_paymentmethod_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='amount',
            new_name='paid_amount',
        ),
    ]
