# Generated by Django 4.1.3 on 2023-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0023_rename_amount_paymentmethod_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='back_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='received_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
