# Generated by Django 4.1.3 on 2023-04-18 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0025_invoice_customer_email_invoice_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sale_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
