# Generated by Django 4.1.3 on 2023-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0026_invoice_sale_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DianResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_number', models.CharField(max_length=255, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_number', models.PositiveIntegerField()),
                ('to_number', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
