# Generated by Django 4.1.3 on 2023-04-21 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0027_dianresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='dianresolution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dian_resolution', to=settings.AUTH_USER_MODEL),
        ),
    ]
