# Generated by Django 4.1.3 on 2023-04-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0028_dianresolution_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dianresolution',
            old_name='next_number',
            new_name='current_number',
        ),
    ]
