# Generated by Django 4.1.3 on 2023-04-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0030_alter_dianresolution_current_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
