# Generated by Django 4.1.3 on 2023-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0031_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
    ]
