# Generated by Django 4.1.3 on 2023-05-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0034_alter_inventory_options_storageinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('code',)},
        ),
    ]
