# Generated by Django 4.1.3 on 2023-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0036_delete_storageinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='remaining',
            new_name='remaining_in_shops',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='total',
            new_name='total_in_shops',
        ),
        migrations.AddField(
            model_name='inventory',
            name='buying_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='remaining_in_storage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_in_storage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
