# Generated by Django 4.1.3 on 2023-05-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0037_rename_remaining_inventory_remaining_in_shops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='remaining_in_shops',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_in_shops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
