# Generated by Django 4.1.3 on 2024-02-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0039_alter_inventory_total_in_storage_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='Nit',
            new_name='nit',
        ),
    ]
