# Generated by Django 4.1.3 on 2024-02-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0039_remove_inventory_remaining_in_shops_and_more'),
        ('app_control', '0040_rename_nit_provider_nit'),
    ]

    operations = [
    ]
