# Generated by Django 4.1.3 on 2024-02-28 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_control', '0041_merge_20240228_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_wireless', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_terminals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
