# Generated by Django 4.1.3 on 2024-02-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0042_paymentterminal_remove_inventory_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_terminal', to='app_control.paymentterminal'),
        ),
    ]
