# Generated by Django 4.1.3 on 2024-03-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0043_invoice_payment_terminal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_dollar',
            new_name='is_dolar',
        ),
    ]
