# Generated by Django 4.1.3 on 2024-03-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0044_rename_is_dollar_invoice_is_dolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shop',
        ),
    ]
