# Generated by Django 4.1.3 on 2024-03-05 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0045_remove_invoice_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_dolar',
            new_name='is_dollar',
        ),
    ]
